### ISSUE TITLE
build failed on macOS

### ISSUE THREAD

**Issue by abit-me** [0xeb/ida-climacros#2]
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/23404784/103354185-d9625b00-4ae5-11eb-9a08-c4d697db5782.png">

**Comment by 0xeb** [comment]
Thank you. Please get latest version. I don't have macOS handy but I fixed the issue on Linux. Let me know if that works.

**Comment by abit-me** [comment]
> Thank you. Please get latest version. I don't have macOS handy but I fixed the issue on Linux. Let me know if that works.

I'm sorry, but it still has many build errors

**Comment by abit-me** [comment]
I change some of your code to fix some build errors.
#include "utils_impl.cpp"  ->  #include "utils_impl.hpp"
and
const int macro_editor_t::widths_[3]         = { 10, 30, 70 };
const char *const macro_editor_t::header_[3] = { "Macro", "Expression", "Description" };
inline macro_editor_t::macro_editor_t(const char *title_ = "CLI macros editor")
        : chooser_t(flags_, qnumber(widths_), widths_, header_, title_)
{
}
->
static constexpr int g_widths[3]                  = { 10, 30, 70 };
static constexpr const char *const g_header[3]    = { "Macro", "Expression", "Description" };
public:
    macro_editor_t(const char *title_ = "CLI macros editor")
            : chooser_t(flags_, qnumber(g_widths), g_widths, g_header, title_)
    {
    }

It build success, but IDA Pro 7.5 is Crashed.
<img width="816" alt="Screen Shot 2021-01-07 at 17 06 14" src="https://user-images.githubusercontent.com/23404784/103873401-b13cb280-510a-11eb-9691-af7c928ce72e.png">

crashed at this point
<img width="2560" alt="Screen Shot 2021-01-07 at 17 14 46" src="https://user-images.githubusercontent.com/23404784/103874280-f1506500-510b-11eb-811e-1ad8274c3fd7.png">

**Comment by abit-me** [comment]
I fixed the regex crash
        // Form the single regular expression
        re_replace = re_str;
->
    // Form the single regular expression
    try
    {
        re_replace = std::regex(re_str, std::regex_constants::egrep);
    }
    catch (std::regex_error& e)
    {
        LOG_F(INFO, "(regex_error(%d) %s)", e.code(), e.what());
    }
